language: node_js
node_js:
  - "stable"
postgres:
  adapter: postgresql
  database: myapp_polaroid
  username: postgres
before_script:
  - "psql -c 'create database myapp_polaroid;' -U postgres"
script:
  - yarn build
  - yarn serve
